apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-217-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - nightly-updater.yaml

images:
  - name: app-217-backend
    newName: ghcr.io/jobucaldas/app-217-backend
    newTag: nightly
  - name: app-217-frontend
    newName: ghcr.io/jobucaldas/app-217-frontend
    newTag: nightly

patches:
  - path: pod-spec.yaml
    target:
      kind: Deployment
  - path: pull-always-backend.yaml
  - path: pull-always-frontend.yaml

configMapGenerator:
  - name: app-217-backend-config
    literals:
      - APP_ENV=development
      - APP_BASE_URL=https://encom.tailbe71e1.ts.net:8443

generatorOptions:
  disableNameSuffixHash: true
